/* global Icon, Kamon, React */

// ═══════════════════════════════════════════════════════════════════════════
// L5 · WORK — documents, tasks generated from memory
// ═══════════════════════════════════════════════════════════════════════════
function ScreenWork() {
  return (
    <div className="content-inner">
      <div className="page-head">
        <div>
          <div className="t-mono" style={{marginBottom:8}}>OPERATIONS LAYER</div>
          <h1>Work <span className="jp">任務</span></h1>
          <div className="sub">Documents and tasks generated by SHOGUN from your memory. Editable, owned by you.</div>
        </div>
        <div className="row">
          <button className="btn btn-secondary"><Icon name="filter" size={14}/>All types</button>
          <button className="btn btn-primary"><Icon name="plus" size={14}/>New document</button>
        </div>
      </div>

      <div style={{display:'grid', gridTemplateColumns:'1fr 1fr 1fr', gap:16, marginBottom:32}}>
        {[
          {t:'Pricing page draft', tag:'MARKDOWN', src:'Rev-cat chat · Matt 1-on-1', when:'14:08', status:'draft'},
          {t:'Weekly review · Apr 14', tag:'DOC', src:'23 memories · last week', when:'Apr 14', status:'final'},
          {t:'SHOGUN IA v2', tag:'DOC', src:'Matt feedback · Toru review', when:'Apr 16', status:'in-review'},
        ].map((d,i) => (
          <div key={i} className="card card-interactive" style={{padding:0, overflow:'hidden'}}>
            <div style={{padding:'14px 18px', background:'var(--surface-2)', borderBottom:'1px solid var(--border)', display:'flex', alignItems:'center', gap:10}}>
              <Icon name="file" size={14} className="gold"/>
              <span className="t-mono" style={{fontSize:10}}>{d.tag}</span>
              <span className="spacer"/>
              <span className={d.status==='final'?'label label-success':d.status==='draft'?'label label-gold':'label'}>{d.status}</span>
            </div>
            <div style={{padding:20}}>
              <div style={{fontSize:15, fontWeight:500, marginBottom:12}}>{d.t}</div>
              <div style={{fontSize:12, color:'var(--text-dim)', marginBottom:16}}>From: {d.src}</div>
              <div className="stack-2">
                <div style={{height:6, background:'var(--surface-2)', borderRadius:3, width:'96%'}}/>
                <div style={{height:6, background:'var(--surface-2)', borderRadius:3, width:'82%'}}/>
                <div style={{height:6, background:'var(--surface-2)', borderRadius:3, width:'70%'}}/>
              </div>
            </div>
            <div style={{padding:'12px 18px', borderTop:'1px solid var(--border)', display:'flex', alignItems:'center', gap:10}}>
              <span className="t-mono" style={{fontSize:10}}>{d.when}</span>
              <span className="spacer"/>
              <Icon name="link" size={12} className="dim"/>
              <span style={{fontSize:11, color:'var(--text-dim)'}}>{i+3} memories</span>
            </div>
          </div>
        ))}
      </div>

      {/* Tasks */}
      <div style={{fontSize:13, fontWeight:500, marginBottom:14, color:'var(--text-mute)'}}>Tasks · surfaced from memory</div>
      <div className="card" style={{padding:0}}>
        {[
          ['Draft pricing page', 'From Rev-cat CTO chat · today', 'due tomorrow', true],
          ['Follow up with Matt on Q2 roadmap', 'From All PJ meeting', 'today 17:00'],
          ['Reply to Elevenlabs intro', 'From Gmail thread', 'no deadline'],
          ['Decide on BYOK vs hosted default', 'Open since Apr 10', 'flagged 3x'],
        ].map((t,i) => (
          <div key={i} className="row" style={{padding:'14px 20px', borderBottom:i<3?'1px solid var(--border)':'none', gap:14}}>
            <div style={{width:16, height:16, border:'1.5px solid '+(t[3]?'var(--gold)':'var(--border-hi)'), borderRadius:'var(--radius-sm)', display:'flex', alignItems:'center', justifyContent:'center'}}>
              {t[3] && <Icon name="check" size={10} className="gold"/>}
            </div>
            <div style={{flex:1}}>
              <div style={{fontSize:14}}>{t[0]}</div>
              <div style={{fontSize:11, color:'var(--text-dim)', marginTop:2}}>{t[1]}</div>
            </div>
            <span className="label">{t[2]}</span>
            <button className="btn btn-sm btn-ghost"><Icon name="more" size={14}/></button>
          </div>
        ))}
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// L6 · CAPTURE — ingest (Accessibility API, not screenshots)
// ═══════════════════════════════════════════════════════════════════════════
function ScreenCapture() {
  return (
    <div className="content-inner">
      <div className="page-head">
        <div>
          <div className="t-mono" style={{marginBottom:8}}>INGEST LAYER</div>
          <h1>Capture <span className="jp">捕捉</span></h1>
          <div className="sub">SHOGUN reads your day passively via macOS Accessibility. Never screenshots. Never OCR. Local only.</div>
        </div>
        <div className="row">
          <span className="label label-success"><span style={{width:6, height:6, borderRadius:'50%', background:'var(--success)', marginRight:6, boxShadow:'0 0 0 3px rgba(107,158,120,0.2)'}}/>CAPTURING</span>
          <button className="btn btn-secondary"><Icon name="pause" size={14}/>Pause</button>
        </div>
      </div>

      {/* Live stream */}
      <div style={{display:'grid', gridTemplateColumns:'1.5fr 1fr', gap:20, marginBottom:32}}>
        <div className="card" style={{padding:0, overflow:'hidden'}}>
          <div style={{padding:'16px 20px', borderBottom:'1px solid var(--border)', display:'flex', alignItems:'center'}}>
            <div style={{fontSize:13, fontWeight:500}}>Live capture</div>
            <span className="label label-gold" style={{marginLeft:10}}>TAIL -F</span>
            <span className="spacer"/>
            <span className="t-mono" style={{fontSize:10}}>24 EVENTS / MIN</span>
          </div>
          <div style={{padding:'4px 0', fontFamily:'var(--font-mono)', fontSize:12, maxHeight:280, overflowY:'auto'}}>
            {[
              ['14:32:08', 'chrome', 'url: notion.so/100x-user-framework'],
              ['14:31:54', 'claude', 'msg_in · 142 tokens'],
              ['14:31:41', 'claude', 'msg_out · 518 tokens'],
              ['14:30:22', 'slack', 'dm from Matt · 3 lines'],
              ['14:28:10', 'vscode', 'file: shogun/app.tsx · 42 edits'],
              ['14:25:00', 'chrome', 'url: revenuecat.com/pricing'],
              ['14:22:17', 'claude', 'new conversation: rev-cat pricing'],
              ['14:18:00', 'terminal', 'cmd: git commit -m "ia v2"'],
            ].map((l,i)=>(
              <div key={i} className="row" style={{padding:'6px 20px', gap:14, borderBottom:'1px dashed var(--border)'}}>
                <span style={{color:'var(--text-dim)'}}>{l[0]}</span>
                <span className="gold" style={{minWidth:70}}>{l[1]}</span>
                <span style={{color:'var(--text-mute)'}}>{l[2]}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Stats */}
        <div className="stack-4">
          <div className="card" style={{padding:20}}>
            <div className="t-mono" style={{marginBottom:12}}>TODAY · CAPTURED</div>
            <div style={{display:'grid', gridTemplateColumns:'1fr 1fr', gap:16}}>
              <div><div style={{fontSize:32, fontWeight:600}}>1,248</div><div style={{fontSize:11, color:'var(--text-dim)'}}>events</div></div>
              <div><div style={{fontSize:32, fontWeight:600}}>23</div><div style={{fontSize:11, color:'var(--text-dim)'}}>memories</div></div>
            </div>
            <div style={{height:1, background:'var(--border)', margin:'16px 0'}}/>
            <div style={{fontSize:12, color:'var(--text-mute)', lineHeight:1.6}}>
              Captured via Accessibility API · <span className="gold">0 screenshots taken</span> · <span className="gold">0 OCR runs</span>
            </div>
          </div>

          <div className="card" style={{padding:20}}>
            <div className="t-mono" style={{marginBottom:12}}>APP COVERAGE</div>
            {[
              ['Claude', 542, 94],
              ['Chrome', 318, 72],
              ['Slack', 142, 68],
              ['VSCode', 98, 40],
              ['Gmail', 76, 52],
            ].map(([n,c,w],i)=>(
              <div key={i} style={{marginBottom:10}}>
                <div className="row" style={{marginBottom:4}}>
                  <span style={{fontSize:12}}>{n}</span>
                  <span className="spacer"/>
                  <span className="t-mono" style={{fontSize:10}}>{c}</span>
                </div>
                <div style={{height:3, background:'var(--surface-2)', borderRadius:2, overflow:'hidden'}}>
                  <div style={{height:'100%', width:w+'%', background:'var(--gold)'}}/>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Permissions card */}
      <div className="card" style={{padding:20, background:'var(--surface-2)', borderColor:'var(--border-hi)'}}>
        <div className="row" style={{marginBottom:12}}>
          <Icon name="shield" size={16} className="gold"/>
          <div style={{fontSize:14, fontWeight:500}}>What SHOGUN can see</div>
          <span className="spacer"/>
          <button className="btn btn-sm btn-ghost">Manage permissions <Icon name="arrowUpRight" size={12}/></button>
        </div>
        <div style={{display:'grid', gridTemplateColumns:'repeat(4, 1fr)', gap:12}}>
          {[
            ['Accessibility','Granted','on'],
            ['Calendar','Granted','on'],
            ['Contacts','Not granted','off'],
            ['Screen recording','Not requested','off'],
          ].map(([n,s,o],i)=>(
            <div key={i} style={{padding:12, border:'1px solid var(--border)', borderRadius:'var(--radius-md)', background:'var(--bg)'}}>
              <div className="row" style={{marginBottom:6}}>
                <span style={{fontSize:12}}>{n}</span>
                <span className="spacer"/>
                <div className={'switch '+(o==='on'?'on':'')} style={{transform:'scale(0.8)', transformOrigin:'right'}}/>
              </div>
              <div className="t-mono" style={{fontSize:9, color: o==='on'?'var(--success)':'var(--text-dim)'}}>{s.toUpperCase()}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// L7 · INTEGRATIONS — MCP tools, apps
// ═══════════════════════════════════════════════════════════════════════════
function ScreenIntegrations() {
  const tools = [
    {name:'Gmail', cat:'Mail', jp:'メール', connected:true, ops:['read','draft','send']},
    {name:'Google Calendar', cat:'Calendar', jp:'予定', connected:true, ops:['read','create']},
    {name:'Slack', cat:'Chat', jp:'会話', connected:true, ops:['read','post']},
    {name:'Notion', cat:'Docs', jp:'文書', connected:true, ops:['read','write']},
    {name:'Linear', cat:'Tasks', jp:'課題', connected:true, ops:['read','create']},
    {name:'GitHub', cat:'Code', jp:'コード', connected:true, ops:['read','comment']},
    {name:'Arc Browser', cat:'Web', jp:'閲覧', connected:true, ops:['capture']},
    {name:'Claude', cat:'LLM', jp:'対話', connected:true, ops:['chat']},
    {name:'Figma', cat:'Design', jp:'意匠', connected:false, ops:['read']},
    {name:'Raycast', cat:'Launcher', jp:'起動', connected:false, ops:['trigger']},
    {name:'Obsidian', cat:'Notes', jp:'手記', connected:false, ops:['read','write']},
    {name:'Zapier MCP', cat:'Bridge', jp:'橋梁', connected:false, ops:['any']},
  ];

  return (
    <div className="content-inner">
      <div className="page-head">
        <div>
          <div className="t-mono" style={{marginBottom:8}}>CONNECTION LAYER</div>
          <h1>Integrations <span className="jp">接続</span></h1>
          <div className="sub">20 MCP tools. Your agents use these to act on the outside world.</div>
        </div>
        <div className="row">
          <div style={{fontSize:13, color:'var(--text-mute)'}}><span className="gold" style={{fontSize:20, fontWeight:600}}>8</span> / 20 connected</div>
          <button className="btn btn-primary"><Icon name="plus" size={14}/>Add tool</button>
        </div>
      </div>

      <div style={{display:'grid', gridTemplateColumns:'repeat(3, 1fr)', gap:14}}>
        {tools.map((t,i)=>(
          <div key={i} className="card card-hover" style={{padding:20, opacity: t.connected?1:0.6}}>
            <div className="row" style={{marginBottom:14, gap:12}}>
              <div style={{width:40, height:40, border:'1px solid var(--border)', borderRadius:'var(--radius-md)', background:'var(--surface-2)', display:'flex', alignItems:'center', justifyContent:'center'}}>
                <Icon name="plug" size={16} className={t.connected?'gold':'dim'}/>
              </div>
              <div style={{flex:1}}>
                <div style={{fontSize:14, fontWeight:500}}>{t.name}</div>
                <div className="row" style={{gap:6, marginTop:2}}>
                  <span className="t-mono" style={{fontSize:10}}>{t.cat}</span>
                  <span className="jp dim" style={{fontSize:10}}>{t.jp}</span>
                </div>
              </div>
              <div className={'switch '+(t.connected?'on':'')} style={{transform:'scale(0.85)'}}/>
            </div>
            <div className="row" style={{gap:4, flexWrap:'wrap'}}>
              {t.ops.map(o => <span key={o} className="label" style={{fontSize:10, height:20}}>{o}</span>)}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// L8 · SETTINGS — system layer, BYOK, privacy
// ═══════════════════════════════════════════════════════════════════════════
function ScreenSettings() {
  return (
    <div className="content-inner">
      <div className="page-head">
        <div>
          <div className="t-mono" style={{marginBottom:8}}>SYSTEM LAYER</div>
          <h1>Settings <span className="jp">設定</span></h1>
          <div className="sub">Your keys. Your machine. Your data.</div>
        </div>
      </div>

      <div style={{display:'grid', gridTemplateColumns:'200px 1fr', gap:40}}>
        <div className="stack-2">
          {['Profile','BYOK · Keys','Storage','Privacy','Dream cycle','Billing','Danger zone'].map((s,i)=>(
            <div key={i} className="nav-item" style={{background: i===1?'var(--surface-2)':'transparent', borderColor: i===1?'var(--border)':'transparent', color: i===1?'var(--text)':'var(--text-mute)'}}>
              <span>{s}</span>
            </div>
          ))}
        </div>

        <div className="stack-6" style={{maxWidth:680}}>
          {/* BYOK */}
          <div className="card" style={{padding:24}}>
            <div className="row" style={{marginBottom:6}}>
              <Icon name="key" size={16} className="gold"/>
              <div style={{fontSize:16, fontWeight:500}}>Bring your own key</div>
            </div>
            <div style={{fontSize:13, color:'var(--text-mute)', lineHeight:1.6, marginBottom:20}}>
              SHOGUN does not proxy your LLM calls. Your keys, your billing, your rate limits. We never see prompts or responses.
            </div>
            <div className="stack-4">
              {[
                ['Anthropic', 'sk-ant-•••••••••••••••••••••••w72A', true],
                ['OpenAI', 'sk-proj-•••••••••••••••••••••jR8k', true],
                ['Google AI', 'not configured', false],
              ].map(([p,k,ok],i)=>(
                <div key={i} className="row" style={{padding:'12px 16px', background:'var(--surface-2)', border:'1px solid var(--border)', borderRadius:'var(--radius-md)', gap:12}}>
                  <div style={{width:28, height:28, background:'var(--bg)', border:'1px solid var(--border)', borderRadius:'var(--radius-sm)', display:'flex', alignItems:'center', justifyContent:'center'}}>
                    <Icon name="key" size={12} className={ok?'gold':'dim'}/>
                  </div>
                  <div style={{flex:1}}>
                    <div style={{fontSize:13, fontWeight:500}}>{p}</div>
                    <div style={{fontSize:11, color: ok?'var(--text-dim)':'var(--text-dim)', fontFamily:ok?'var(--font-mono)':'inherit', marginTop:2}}>{k}</div>
                  </div>
                  {ok ? <span className="label label-success">ACTIVE</span> : <button className="btn btn-sm btn-secondary">Add</button>}
                </div>
              ))}
            </div>
          </div>

          {/* Privacy */}
          <div className="card" style={{padding:24}}>
            <div className="row" style={{marginBottom:20}}>
              <Icon name="shield" size={16} className="gold"/>
              <div style={{fontSize:16, fontWeight:500}}>Privacy posture</div>
              <span className="spacer"/>
              <span className="label label-success">AUDITED</span>
            </div>
            {[
              ['Local storage', 'All memories stored on this Mac · pgvector', true],
              ['Zero cloud sync', 'Nothing leaves your device unless you act', true],
              ['No screenshots', 'SHOGUN reads via Accessibility API only', true],
              ['No telemetry', 'Anonymous usage metrics: opt-in', false],
            ].map(([l,d,on],i)=>(
              <div key={i} className="row" style={{padding:'14px 0', borderBottom:i<3?'1px solid var(--border)':'none', gap:14}}>
                <div style={{flex:1}}>
                  <div style={{fontSize:13, fontWeight:500}}>{l}</div>
                  <div style={{fontSize:12, color:'var(--text-dim)', marginTop:2}}>{d}</div>
                </div>
                <div className={'switch '+(on?'on':'')}/>
              </div>
            ))}
          </div>

          {/* Storage */}
          <div className="card" style={{padding:24}}>
            <div className="row" style={{marginBottom:16}}>
              <Icon name="database" size={16} className="gold"/>
              <div style={{fontSize:16, fontWeight:500}}>Storage</div>
              <span className="spacer"/>
              <span className="t-mono">~/Library/SHOGUN</span>
            </div>
            <div style={{display:'grid', gridTemplateColumns:'repeat(3, 1fr)', gap:16, marginBottom:16}}>
              <div><div style={{fontSize:24, fontWeight:600}}>12,408</div><div style={{fontSize:11, color:'var(--text-dim)'}}>memories</div></div>
              <div><div style={{fontSize:24, fontWeight:600}}>3.4 GB</div><div style={{fontSize:11, color:'var(--text-dim)'}}>on disk</div></div>
              <div><div style={{fontSize:24, fontWeight:600}}>68 days</div><div style={{fontSize:11, color:'var(--text-dim)'}}>history</div></div>
            </div>
            <div style={{height:6, background:'var(--surface-2)', borderRadius:3, overflow:'hidden', marginBottom:8}}>
              <div style={{width:'22%', height:'100%', background:'var(--gold)'}}/>
            </div>
            <div style={{fontSize:11, color:'var(--text-dim)'}}>3.4 GB of 15 GB allocated</div>
          </div>
        </div>
      </div>
    </div>
  );
}

window.ScreenWork = ScreenWork;
window.ScreenCapture = ScreenCapture;
window.ScreenIntegrations = ScreenIntegrations;
window.ScreenSettings = ScreenSettings;
